sequenceDiagram
    participant Client
    participant JSONSchema
    participant Permission
    participant Route

    Client ->> JSONSchema: Hello! I have data
    Validation -->> Client: 409: `drop_table_name` not allowed
    Note right of Validation: using JSON Schemas
    Validation ->> Permission: Data is valid
    Permission -->> Client: 403: YOU SHALL NOT PASS!
    Permission ->> Route: Data is allowed
    Route ->> Client: I'll take that data and give you other data in return
    Note right of Route: All this so you can <br/> put a border and <br/> a shadow over it
